import type {
  Restaurant,
  Product,
  Category,
  Coupon,
  Allergen,
  CategoryId,
  Badge,
} from "./types";

export const CATEGORIES: Category[] = [
  { id: "pizza", name: "Pizza", icon: "🍕" },
  { id: "burgers", name: "Burgery", icon: "🍔" },
  { id: "sandwiches", name: "Club Sandwich", icon: "🥪" },
  { id: "sides", name: "Ostatné", icon: "🍟" },
  { id: "sauces", name: "Dresingy / Omáčky", icon: "🥫" },
  { id: "drinks", name: "Nápoje", icon: "🥤" },
];

// Allergen legend as printed on the Pyro menu.
export const ALLERGENS: Allergen[] = [
  { code: "1", name: "Obilniny s lepkom" },
  { code: "2", name: "Kôrovce" },
  { code: "3", name: "Vajcia" },
  { code: "4", name: "Ryby" },
  { code: "5", name: "Arašidy" },
  { code: "6", name: "Sójové zrná" },
  { code: "7", name: "Mlieko" },
  { code: "8", name: "Orechy" },
  { code: "9", name: "Zeler" },
  { code: "10", name: "Horčica" },
  { code: "11", name: "Sezamové semená" },
  { code: "12", name: "Oxid siričitý a siričitany" },
  { code: "13", name: "Vlčí bôb" },
  { code: "14", name: "Mäkkýše" },
];

export const RESTAURANTS: Restaurant[] = [
  {
    id: "pyro",
    name: "Pyro Pizzeria",
    logo: "/logos/pyro.svg",
    logoName: "Pyro",
    logoTag: "PIZZA · BURGER",
    tagline: "Pravá pec, pravá chuť.",
    soldOutNote:
      "Na dnes máme vypredané — ďakujeme za priazeň! Objednávky opäť v ďalší otvárací deň.",
    heroLine1: "PRAVÁ PEC,",
    heroLine2: "PRAVÁ CHUŤ",
    city: "Kamenná Poruba",
    address: "Hlavná 29/65, Kamenná Poruba",
    phone: "+421 904 117 770",
    email: "pyro.pizzeria@gmail.com",
    image:
      "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=2000&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1595854341625-f33ee10dbf94?w=800&q=80",
      "https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=800&q=80",
      "https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=800&q=80",
    ],
    lat: 49.1725,
    lng: 18.6231,
    prepTimeMinutes: 45,
    accent: "#E85D04",
    // Po–St zatvorené · Štv/Ned 16:00–21:00 · Pi/So 16:00–22:00
    openingHours: [
      { day: 0, open: "16:00", close: "21:00", closed: true },
      { day: 1, open: "16:00", close: "21:00", closed: true },
      { day: 2, open: "16:00", close: "21:00", closed: true },
      { day: 3, open: "16:00", close: "21:00" },
      { day: 4, open: "16:00", close: "22:00" },
      { day: 5, open: "16:00", close: "22:00" },
      { day: 6, open: "16:00", close: "21:00" },
    ],
    // Rozvoz zadarmo. Do Rajca doručujeme až od 15 €.
    deliveryZones: [
      {
        id: "pyro-a",
        name: "Kamenná Poruba a okolie",
        minimumOrder: 0,
        deliveryFee: 0,
        estimatedMinutes: 45,
        areas: ["Kamenná Poruba", "Poluvsie", "Hlavná", "Školská", "Záhradná"],
      },
      {
        id: "pyro-rajec",
        name: "Rajec a okolie",
        minimumOrder: 0,
        deliveryFee: 0,
        estimatedMinutes: 45,
        areas: [
          "Rajec",
          "Rajecké Teplice",
          "Konská",
          "Kunerad",
          "Kaplna",
          "Zbyňov",
          "Kľače",
        ],
      },
    ],
  },
  {
    id: "polomarik",
    name: "Polomárik Pizzeria",
    logo: "/logos/polomarik.svg",
    logoName: "Polomárik",
    logoTag: "PIZZERIA",
    tagline: "Domáca pohoda pod Malou Fatrou.",
    soldOutNote:
      "Na dnes máme vypredané — ďakujeme za priazeň! Objednávky opäť v ďalší otvárací deň.",
    heroLine1: "DOMÁCA POHODA",
    heroLine2: "POD MALOU FATROU",
    city: "Stráňavy",
    address: "Stráňavy 435, 013 25",
    phone: "+421 908 333 444",
    email: "objednavky@polomarik.sk",
    image:
      "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=2000&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80",
      "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800&q=80",
      "https://images.unsplash.com/photo-1552539618-7eec9b4d1796?w=800&q=80",
    ],
    lat: 49.171,
    lng: 18.8342,
    prepTimeMinutes: 40,
    accent: "#F5B301",
    // Po–St zatvorené · Štv/Ned 16:00–21:00 · Pi/So 16:00–22:00
    openingHours: [
      { day: 0, open: "16:00", close: "21:00", closed: true },
      { day: 1, open: "16:00", close: "21:00", closed: true },
      { day: 2, open: "16:00", close: "21:00", closed: true },
      { day: 3, open: "16:00", close: "21:00" },
      { day: 4, open: "16:00", close: "22:00" },
      { day: 5, open: "16:00", close: "22:00" },
      { day: 6, open: "16:00", close: "21:00" },
    ],
    // Rozvoz zadarmo.
    deliveryZones: [
      {
        id: "polo-a",
        name: "Stráňavy a okolie",
        minimumOrder: 0,
        deliveryFee: 0,
        estimatedMinutes: 40,
        areas: ["Stráňavy", "Nová", "Pri Potoku", "Fatranská"],
      },
      {
        id: "polo-b",
        name: "Strečno · Varín · okolie",
        minimumOrder: 0,
        deliveryFee: 0,
        estimatedMinutes: 50,
        areas: [
          "Strečno",
          "Nezbudská Lúčka",
          "Dolná Tižina",
          "Gbeľany",
          "Varín",
        ],
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// Real Pyro menu (from the printed Pizza / Burger / Club Sandwich menu).
// Each item is a compact tuple; buildMenu() expands it into a Product per
// restaurant. Pizzas keep a single listed size (with the printed weight); the
// "Prispôsobiť" customizer still lets guests add / remove toppings.
// ---------------------------------------------------------------------------

type MenuItem = {
  slug: string;
  category: CategoryId;
  name: string;
  weight: string; // e.g. "720g", "0,5l"
  price: number; // €
  desc: string;
  ingredients: string[];
  allergens: string[];
  badges: Badge[];
};

const IMAGES: Record<CategoryId, string[]> = {
  pizza: [
    "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80",
    "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800&q=80",
    "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=800&q=80",
    "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?w=800&q=80",
    "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=800&q=80",
    "https://images.unsplash.com/photo-1511689660979-10d2b1aada49?w=800&q=80",
    "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80",
    "https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=800&q=80",
  ],
  burgers: [
    "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80",
    "https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&q=80",
    "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=800&q=80",
    "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=800&q=80",
  ],
  sandwiches: [
    "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&q=80",
    "https://images.unsplash.com/photo-1539252554453-80ab65ce3586?w=800&q=80",
    "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&q=80",
    "https://images.unsplash.com/photo-1509722747041-616f39b57569?w=800&q=80",
  ],
  sides: [
    "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800&q=80",
    "https://images.unsplash.com/photo-1639024471283-03518883512d?w=800&q=80",
    "https://images.unsplash.com/photo-1608039755401-742074f0548d?w=800&q=80",
    "https://images.unsplash.com/photo-1562967914-608f82629710?w=800&q=80",
  ],
  sauces: [
    "https://images.unsplash.com/photo-1607013251379-e6eecfffe234?w=800&q=80",
    "https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=800&q=80",
  ],
  drinks: [
    "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=800&q=80",
    "https://images.unsplash.com/photo-1560023907-5f339617ea30?w=800&q=80",
  ],
};

const MENU: MenuItem[] = [
  // ---------------- PIZZA ----------------
  {
    slug: "quattro-formaggi",
    category: "pizza",
    name: "Quattro Formaggi",
    weight: "720g",
    price: 10.5,
    desc: "Drvené paradajky, mozzarella, eidam, údený syr, niva.",
    ingredients: ["Drvené paradajky", "Mozzarella", "Eidam", "Údený syr", "Niva"],
    allergens: ["1", "7", "12"],
    badges: ["bestseller"],
  },
  {
    slug: "margheritta",
    category: "pizza",
    name: "Margheritta",
    weight: "600g",
    price: 9.9,
    desc: "Drvené paradajky, mozzarella, bazalka, olivový olej.",
    ingredients: ["Drvené paradajky", "Mozzarella", "Bazalka", "Olivový olej"],
    allergens: ["1", "7", "12"],
    badges: ["vegetarian", "bestseller"],
  },
  {
    slug: "polo",
    category: "pizza",
    name: "Polo",
    weight: "690g",
    price: 10.3,
    desc: "Drvené paradajky, mozzarella, šunka, kukurica.",
    ingredients: ["Drvené paradajky", "Mozzarella", "Šunka", "Kukurica"],
    allergens: ["1", "7", "12"],
    badges: [],
  },
  {
    slug: "prosciutto",
    category: "pizza",
    name: "Prosciutto",
    weight: "660g",
    price: 10.3,
    desc: "Drvené paradajky, mozzarella, prosciutto, rukola, parmezán.",
    ingredients: ["Drvené paradajky", "Mozzarella", "Prosciutto", "Rukola", "Parmezán"],
    allergens: ["1", "7", "12"],
    badges: ["recommended"],
  },
  {
    slug: "diablo",
    category: "pizza",
    name: "Diablo",
    weight: "770g",
    price: 10.9,
    desc: "Drvené paradajky, mozzarella, pikantná saláma, feferóny, klobása, cibuľa, chilli omáčka, cesnak.",
    ingredients: [
      "Drvené paradajky",
      "Mozzarella",
      "Pikantná saláma",
      "Feferóny",
      "Klobása",
      "Cibuľa",
      "Chilli omáčka",
      "Cesnak",
    ],
    allergens: ["1", "7", "12"],
    badges: ["spicy", "recommended"],
  },
  {
    slug: "polomar",
    category: "pizza",
    name: "Polomar",
    weight: "750g",
    price: 10.7,
    desc: "Drvené paradajky, mozzarella, údené mäso, niva, encián.",
    ingredients: ["Drvené paradajky", "Mozzarella", "Údené mäso", "Niva", "Encián"],
    allergens: ["1", "7", "12"],
    badges: [],
  },
  {
    slug: "gazdovska",
    category: "pizza",
    name: "Gazdovská",
    weight: "790g",
    price: 11.2,
    desc: "Drvené paradajky, mozzarella, slanina, klobása, kyslá kapusta, bryndza.",
    ingredients: [
      "Drvené paradajky",
      "Mozzarella",
      "Slanina",
      "Klobása",
      "Kyslá kapusta",
      "Bryndza",
    ],
    allergens: ["1", "7", "12"],
    badges: [],
  },
  {
    slug: "bacovska",
    category: "pizza",
    name: "Bačovská",
    weight: "770g",
    price: 10.9,
    desc: "Smotana, mozzarella, bryndza, cibuľa, slanina, údený syr, cesnak.",
    ingredients: [
      "Smotana",
      "Mozzarella",
      "Bryndza",
      "Cibuľa",
      "Slanina",
      "Údený syr",
      "Cesnak",
    ],
    allergens: ["1", "7", "12"],
    badges: [],
  },
  {
    slug: "marcello",
    category: "pizza",
    name: "Marcello",
    weight: "790g",
    price: 11.2,
    desc: "Drvené paradajky, mozzarella, šunka, šampiňóny, niva, vajce, kukurica.",
    ingredients: [
      "Drvené paradajky",
      "Mozzarella",
      "Šunka",
      "Šampiňóny",
      "Niva",
      "Vajce",
      "Kukurica",
    ],
    allergens: ["1", "3", "7", "12"],
    badges: [],
  },
  {
    slug: "etna",
    category: "pizza",
    name: "Etna",
    weight: "820g",
    price: 11.2,
    desc: "Drvené paradajky, mozzarella, cibuľa, šampiňóny, artičoky, slanina, niva, vajce, bazalka.",
    ingredients: [
      "Drvené paradajky",
      "Mozzarella",
      "Cibuľa",
      "Šampiňóny",
      "Artičoky",
      "Slanina",
      "Niva",
      "Vajce",
      "Bazalka",
    ],
    allergens: ["1", "3", "7", "12"],
    badges: [],
  },
  {
    slug: "matello",
    category: "pizza",
    name: "Matello",
    weight: "810g",
    price: 11.5,
    desc: "Drvené paradajky, mozzarella, šunka, klobása, niva, olivy, kukurica, cesnak.",
    ingredients: [
      "Drvené paradajky",
      "Mozzarella",
      "Šunka",
      "Klobása",
      "Niva",
      "Olivy",
      "Kukurica",
      "Cesnak",
    ],
    allergens: ["1", "7", "12"],
    badges: [],
  },
  {
    slug: "anneta",
    category: "pizza",
    name: "Anneta",
    weight: "770g",
    price: 11.2,
    desc: "Drvené paradajky, mozzarella, šunka, saláma, niva, chilli omáčka, smotana.",
    ingredients: [
      "Drvené paradajky",
      "Mozzarella",
      "Šunka",
      "Saláma",
      "Niva",
      "Chilli omáčka",
      "Smotana",
    ],
    allergens: ["1", "7", "12"],
    badges: ["spicy"],
  },
  {
    slug: "spezzia",
    category: "pizza",
    name: "Spezzia",
    weight: "830g",
    price: 11.5,
    desc: "Drvené paradajky, mozzarella, kuracie prsia, niva, encián, šampiňóny, vajce.",
    ingredients: [
      "Drvené paradajky",
      "Mozzarella",
      "Kuracie prsia",
      "Niva",
      "Encián",
      "Šampiňóny",
      "Vajce",
    ],
    allergens: ["1", "3", "7", "12"],
    badges: [],
  },
  {
    slug: "quattro-formaggi-extra",
    category: "pizza",
    name: "Quattro F. Extra",
    weight: "800g",
    price: 11.1,
    desc: "Drvené paradajky, mozzarella, eidam, údený syr, niva, bryndza, smotana.",
    ingredients: [
      "Drvené paradajky",
      "Mozzarella",
      "Eidam",
      "Údený syr",
      "Niva",
      "Bryndza",
      "Smotana",
    ],
    allergens: ["1", "7", "12"],
    badges: [],
  },
  {
    slug: "slovakia",
    category: "pizza",
    name: "Slovakia",
    weight: "790g",
    price: 11.5,
    desc: "Drvené paradajky, mozzarella, šunka, údené mäso, niva, korbáčik, kukurica.",
    ingredients: [
      "Drvené paradajky",
      "Mozzarella",
      "Šunka",
      "Údené mäso",
      "Niva",
      "Korbáčik",
      "Kukurica",
    ],
    allergens: ["1", "7", "12"],
    badges: [],
  },
  {
    slug: "majlo",
    category: "pizza",
    name: "Majlo",
    weight: "800g",
    price: 11.5,
    desc: "Drvené paradajky, mozzarella, korbáčik, jarná cibuľka, pomaly pečená trhaná krkovička, koktailový dresing.",
    ingredients: [
      "Drvené paradajky",
      "Mozzarella",
      "Korbáčik",
      "Jarná cibuľka",
      "Trhaná krkovička",
      "Koktailový dresing",
    ],
    allergens: ["1", "2", "3", "7", "12"],
    badges: ["recommended"],
  },
  {
    slug: "new-york-double-cheese",
    category: "pizza",
    name: "New York Double Cheese",
    weight: "1200g",
    price: 15.9,
    desc: "Drvené paradajky, mozzarella, dvojité cesto — šunkový alebo salámový variant.",
    ingredients: ["Drvené paradajky", "Mozzarella", "Dvojité cesto", "Šunka / saláma"],
    allergens: ["1", "7", "12"],
    badges: ["new"],
  },
  {
    slug: "la-fresca",
    category: "pizza",
    name: "La Fresca",
    weight: "810g",
    price: 12.5,
    desc: "Smotana, červená cibuľa, prosciutto, bazalka, karamelizovaná broskyňa, bryndza, ricotta, chilli med.",
    ingredients: [
      "Smotana",
      "Červená cibuľa",
      "Prosciutto",
      "Bazalka",
      "Karamelizovaná broskyňa",
      "Bryndza",
      "Ricotta",
      "Chilli med",
    ],
    allergens: ["1", "7", "12"],
    badges: ["new", "recommended"],
  },
  {
    slug: "olivia",
    category: "pizza",
    name: "Olivia",
    weight: "860g",
    price: 12.5,
    desc: "Drvené paradajky, mozzarella, prosciutto, olivy, ricotta, bazalkové pesto.",
    ingredients: [
      "Drvené paradajky",
      "Mozzarella",
      "Prosciutto",
      "Olivy",
      "Ricotta",
      "Bazalkové pesto",
    ],
    allergens: ["1", "7", "12"],
    badges: [],
  },
  {
    slug: "pistachio-crush",
    category: "pizza",
    name: "Pistachio Crush",
    weight: "615g",
    price: 12.5,
    desc: "Drvené paradajky, mozzarella, prosciutto cotto, baby špenát, karamelizovaná cibuľa, drvené pistácie.",
    ingredients: [
      "Drvené paradajky",
      "Mozzarella",
      "Prosciutto cotto",
      "Baby špenát",
      "Karamelizovaná cibuľa",
      "Drvené pistácie",
    ],
    allergens: ["1", "3", "5", "7", "8", "12"],
    badges: ["new", "recommended"],
  },
  {
    slug: "pizza-tycinky",
    category: "pizza",
    name: "Pizza tyčinky",
    weight: "360g",
    price: 6.2,
    desc: "Pizza cesto — čisté alebo s bazalkovým pesto.",
    ingredients: ["Pizza cesto", "Bazalkové pesto"],
    allergens: ["1", "3", "7"],
    badges: ["vegetarian"],
  },
  {
    slug: "plnene-stangle",
    category: "pizza",
    name: "Plnené štangle",
    weight: "520g",
    price: 8.0,
    desc: "Pizza cesto, mozzarella, údený syr, eidam, cesnak, olivový olej.",
    ingredients: [
      "Pizza cesto",
      "Mozzarella",
      "Údený syr",
      "Eidam",
      "Cesnak",
      "Olivový olej",
    ],
    allergens: ["1", "3", "7"],
    badges: ["vegetarian"],
  },
  {
    slug: "pizza-uzliky",
    category: "pizza",
    name: "Pizza uzlíky",
    weight: "400g",
    price: 7.0,
    desc: "Pizza cesto, petržlenová vňať, olivový olej, maslo, parmezán, cesnak.",
    ingredients: [
      "Pizza cesto",
      "Petržlenová vňať",
      "Olivový olej",
      "Maslo",
      "Parmezán",
      "Cesnak",
    ],
    allergens: ["1", "7", "12"],
    badges: ["vegetarian"],
  },

  // ---------------- BURGERY ----------------
  {
    slug: "polomar-burger",
    category: "burgers",
    name: "Polomár Burger",
    weight: "520g",
    price: 11.2,
    desc: "Žemľa, sweet & sour omáčka, rukola, trhaná pomaly pečená bravčová krkovička, karamelizovaná cibuľa, grilovaná slanina, hermelín, domáce hranolčeky.",
    ingredients: [
      "Žemľa",
      "Sweet & sour omáčka",
      "Rukola",
      "Trhaná krkovička",
      "Karamelizovaná cibuľa",
      "Grilovaná slanina",
      "Hermelín",
      "Domáce hranolčeky",
    ],
    allergens: ["1", "2", "3", "7", "10", "12"],
    badges: ["bestseller"],
  },
  {
    slug: "cheeseburger",
    category: "burgers",
    name: "Cheeseburger",
    weight: "490g",
    price: 11.2,
    desc: "Žemľa, koktailový dresing, nakladaná uhorka, ľadový šalát, paradajka, mleté hovädzie mäso, cheddar, tekutý cheddar, domáce hranolčeky.",
    ingredients: [
      "Žemľa",
      "Koktailový dresing",
      "Nakladaná uhorka",
      "Ľadový šalát",
      "Paradajka",
      "Mleté hovädzie mäso",
      "Cheddar",
      "Tekutý cheddar",
      "Domáce hranolčeky",
    ],
    allergens: ["1", "2", "3", "7", "10", "12"],
    badges: [],
  },
  {
    slug: "bbq-burger",
    category: "burgers",
    name: "BBQ Burger",
    weight: "490g",
    price: 11.2,
    desc: "Žemľa, BBQ omáčka, nakladaná uhorka, poľníček, mleté hovädzie mäso, cheddar, slanina, nakladaná červená cibuľa, chipotle dresing, domáce hranolčeky.",
    ingredients: [
      "Žemľa",
      "BBQ omáčka",
      "Nakladaná uhorka",
      "Poľníček",
      "Mleté hovädzie mäso",
      "Cheddar",
      "Slanina",
      "Nakladaná červená cibuľa",
      "Chipotle dresing",
      "Domáce hranolčeky",
    ],
    allergens: ["1", "2", "3", "7", "10", "12"],
    badges: ["spicy"],
  },
  {
    slug: "irish-man-burger",
    category: "burgers",
    name: "Irish Man Burger",
    weight: "520g",
    price: 11.2,
    desc: "Žemľa, slaninový dresing, poľníček, trhaná pomaly pečená bravčová krkovička, syr s modrou plesňou, karamelizované jablká na masle s írskou whisky, domáce hranolčeky.",
    ingredients: [
      "Žemľa",
      "Slaninový dresing",
      "Poľníček",
      "Trhaná krkovička",
      "Syr s modrou plesňou",
      "Karamelizované jablká",
      "Domáce hranolčeky",
    ],
    allergens: ["1", "3", "7", "10", "11"],
    badges: ["recommended"],
  },
  {
    slug: "mr-big-burger",
    category: "burgers",
    name: "Mr. Big Burger",
    weight: "630g",
    price: 13.4,
    desc: "Žemľa, domáca burger omáčka, nakladaná uhorka, ľadový šalát, 2× mleté hovädzie mäso, dvojitý cheddar, pečená cibuľa, slanina, domáce hranolčeky.",
    ingredients: [
      "Žemľa",
      "Domáca burger omáčka",
      "Nakladaná uhorka",
      "Ľadový šalát",
      "2× mleté hovädzie mäso",
      "Dvojitý cheddar",
      "Pečená cibuľa",
      "Slanina",
      "Domáce hranolčeky",
    ],
    allergens: ["1", "2", "3", "7", "10", "12"],
    badges: ["bestseller"],
  },

  // ---------------- CLUB SANDWICH ----------------
  {
    slug: "club-kuraci",
    category: "sandwiches",
    name: "Kurací",
    weight: "490g",
    price: 10.1,
    desc: "Grilovaný maslový toast, domáca burger omáčka, poľníček, paradajka, vyprážaná kuracia fileta, volské oko, grilovaná slanina, domáce hranolčeky.",
    ingredients: [
      "Grilovaný maslový toast",
      "Domáca burger omáčka",
      "Poľníček",
      "Paradajka",
      "Vyprážaná kuracia fileta",
      "Volské oko",
      "Grilovaná slanina",
      "Domáce hranolčeky",
    ],
    allergens: ["1", "2", "3", "7", "10", "12"],
    badges: ["bestseller"],
  },
  {
    slug: "club-pyro",
    category: "sandwiches",
    name: "Pyro",
    weight: "460g",
    price: 10.1,
    desc: "Grilovaný maslový toast, slaninový dresing, poľníček, pomaly pečená trhaná krkovička, údený syr, cheddar, mozzarella, červená cibuľka, domáce hranolčeky.",
    ingredients: [
      "Grilovaný maslový toast",
      "Slaninový dresing",
      "Poľníček",
      "Trhaná krkovička",
      "Údený syr",
      "Cheddar",
      "Mozzarella",
      "Červená cibuľka",
      "Domáce hranolčeky",
    ],
    allergens: ["1", "2", "3", "7", "10", "12"],
    badges: ["recommended"],
  },
  {
    slug: "club-smazak",
    category: "sandwiches",
    name: "Smažák",
    weight: "480g",
    price: 10.1,
    desc: "Grilovaný maslový toast, tatárska omáčka, ľadový šalát, vyprážaný syr, paradajka, cibuľové chutney, domáce hranolčeky.",
    ingredients: [
      "Grilovaný maslový toast",
      "Tatárska omáčka",
      "Ľadový šalát",
      "Vyprážaný syr",
      "Paradajka",
      "Cibuľové chutney",
      "Domáce hranolčeky",
    ],
    allergens: ["1", "2", "3", "7", "10", "12"],
    badges: ["vegetarian"],
  },
  {
    slug: "pizza-dog",
    category: "sandwiches",
    name: "Pizza Dog",
    weight: "290g",
    price: 6.5,
    desc: "Pizza cesto, grilovaná klobása, eidam, smažená cibuľka, domáca burger omáčka.",
    ingredients: [
      "Pizza cesto",
      "Grilovaná klobása",
      "Eidam",
      "Smažená cibuľka",
      "Domáca burger omáčka",
    ],
    allergens: ["1", "2", "3", "7", "10", "12"],
    badges: [],
  },
  {
    slug: "yufka",
    category: "sandwiches",
    name: "Yufka",
    weight: "520g",
    price: 6.8,
    desc: "Tortilla, kuracie kebab mäso, cesnakový dresing, ľadový šalát, paradajka, červená kapusta, cibuľa.",
    ingredients: [
      "Tortilla",
      "Kuracie kebab mäso",
      "Cesnakový dresing",
      "Ľadový šalát",
      "Paradajka",
      "Červená kapusta",
      "Cibuľa",
    ],
    allergens: ["1", "2", "3", "7", "10", "12"],
    badges: [],
  },
  {
    slug: "kebab-tanier",
    category: "sandwiches",
    name: "Kebab tanier",
    weight: "520g",
    price: 8.9,
    desc: "Kuracie kebab mäso, cesnakový dresing, ľadový šalát, paradajka, červená kapusta, cibuľa, domáce hranolčeky.",
    ingredients: [
      "Kuracie kebab mäso",
      "Cesnakový dresing",
      "Ľadový šalát",
      "Paradajka",
      "Červená kapusta",
      "Cibuľa",
      "Domáce hranolčeky",
    ],
    allergens: ["1", "2", "3", "7", "10", "12"],
    badges: [],
  },
  {
    slug: "hrancle",
    category: "sandwiches",
    name: "Hrancle",
    weight: "520g",
    price: 8.9,
    desc: "Pomaly pečená trhaná krkovička, citrónovo-cesnakový dresing, jarná a smažená cibuľka, prášok z červenej repy, domáce hranolčeky.",
    ingredients: [
      "Trhaná krkovička",
      "Citrónovo-cesnakový dresing",
      "Jarná a smažená cibuľka",
      "Prášok z červenej repy",
      "Domáce hranolčeky",
    ],
    allergens: ["1", "3", "7", "10"],
    badges: [],
  },
  {
    slug: "hrancle-chilli",
    category: "sandwiches",
    name: "Hrancle Chilli",
    weight: "520g",
    price: 8.9,
    desc: "Pomaly pečená trhaná krkovička, chipotle dresing, jarná a smažená cibuľka, tekutý cheddar, jalapeño, domáce hranolčeky.",
    ingredients: [
      "Trhaná krkovička",
      "Chipotle dresing",
      "Jarná a smažená cibuľka",
      "Tekutý cheddar",
      "Jalapeño",
      "Domáce hranolčeky",
    ],
    allergens: ["1", "3", "7", "10"],
    badges: ["spicy"],
  },

  // ---------------- OSTATNÉ ----------------
  {
    slug: "cibulove-kruzky",
    category: "sides",
    name: "Cibuľové krúžky",
    weight: "150g",
    price: 4.6,
    desc: "Chrumkavé vyprážané cibuľové krúžky.",
    ingredients: ["Cibuľa", "Trojobal"],
    allergens: ["1", "3"],
    badges: ["vegetarian"],
  },
  {
    slug: "kuracie-nugetky",
    category: "sides",
    name: "Kuracie nugetky",
    weight: "140g",
    price: 5.5,
    desc: "Chrumkavé kuracie nugetky.",
    ingredients: ["Kuracie mäso", "Trojobal"],
    allergens: ["1", "3"],
    badges: [],
  },
  {
    slug: "buffalo-kridelka",
    category: "sides",
    name: "Buffalo krídelka",
    weight: "230g",
    price: 5.2,
    desc: "Pikantné buffalo kuracie krídelka.",
    ingredients: ["Kuracie krídelka", "Buffalo omáčka"],
    allergens: ["7"],
    badges: ["spicy"],
  },
  {
    slug: "mozzarella-tycinky",
    category: "sides",
    name: "Mozzarella tyčinky",
    weight: "140g",
    price: 4.5,
    desc: "Vyprážané mozzarellové tyčinky.",
    ingredients: ["Mozzarella", "Trojobal"],
    allergens: ["1", "3", "7"],
    badges: ["vegetarian"],
  },
  {
    slug: "domace-hranolceky",
    category: "sides",
    name: "Domáce hranolčeky",
    weight: "180g",
    price: 2.9,
    desc: "Chrumkavé domáce hranolčeky.",
    ingredients: ["Zemiaky"],
    allergens: [],
    badges: ["vegetarian"],
  },
  {
    slug: "batatove-hranolceky",
    category: "sides",
    name: "Batátové hranolčeky",
    weight: "180g",
    price: 4.0,
    desc: "Batátové hranolčeky.",
    ingredients: ["Batáty"],
    allergens: [],
    badges: ["vegetarian"],
  },
  {
    slug: "langos-gazdovsky",
    category: "sides",
    name: "Langoš gazdovský",
    weight: "260g",
    price: 5.9,
    desc: "Smotana, bryndza, pečená slanina, jarná cibuľka.",
    ingredients: ["Langoš", "Smotana", "Bryndza", "Pečená slanina", "Jarná cibuľka"],
    allergens: ["1", "7"],
    badges: [],
  },
  {
    slug: "langos-cisty",
    category: "sides",
    name: "Langoš čistý / cesnakový",
    weight: "180g",
    price: 2.9,
    desc: "Čistý alebo cesnakový langoš.",
    ingredients: ["Langoš", "Cesnak"],
    allergens: ["1"],
    badges: ["vegetarian"],
  },

  // ---------------- DRESINGY / OMÁČKY ----------------
  {
    slug: "cesnakovy-dresing",
    category: "sauces",
    name: "Cesnakový dresing",
    weight: "50g",
    price: 1.5,
    desc: "Domáci cesnakový dresing.",
    ingredients: ["Cesnak", "Majonéza"],
    allergens: ["3", "7", "10"],
    badges: [],
  },
  {
    slug: "bbq-omacka",
    category: "sauces",
    name: "BBQ omáčka",
    weight: "50g",
    price: 1.5,
    desc: "Dymová BBQ omáčka.",
    ingredients: ["BBQ omáčka"],
    allergens: ["10", "12"],
    badges: ["spicy"],
  },
  {
    slug: "citronovo-cesnakovy-dresing",
    category: "sauces",
    name: "Citrónovo-cesnakový dresing",
    weight: "50g",
    price: 1.5,
    desc: "Sviežy citrónovo-cesnakový dresing.",
    ingredients: ["Citrón", "Cesnak", "Majonéza"],
    allergens: ["3", "7", "10"],
    badges: [],
  },
  {
    slug: "burger-omacka",
    category: "sauces",
    name: "Burger omáčka",
    weight: "50g",
    price: 1.5,
    desc: "Domáca burger omáčka.",
    ingredients: ["Majonéza", "Koreniny"],
    allergens: ["3", "7", "10"],
    badges: [],
  },
  {
    slug: "koktailovy-dresing",
    category: "sauces",
    name: "Koktailový dresing",
    weight: "50g",
    price: 1.5,
    desc: "Koktailový dresing.",
    ingredients: ["Majonéza", "Kečup"],
    allergens: ["3", "7", "10"],
    badges: [],
  },
  {
    slug: "sweet-sour-omacka",
    category: "sauces",
    name: "Sweet & sour omáčka",
    weight: "50g",
    price: 1.5,
    desc: "Sladko-kyslá omáčka.",
    ingredients: ["Sweet & sour omáčka"],
    allergens: ["12"],
    badges: ["vegetarian"],
  },
  {
    slug: "slaninovy-dresing",
    category: "sauces",
    name: "Slaninový dresing",
    weight: "50g",
    price: 1.5,
    desc: "Slaninový dresing.",
    ingredients: ["Slanina", "Majonéza"],
    allergens: ["3", "7"],
    badges: [],
  },
  {
    slug: "sweet-chilli-omacka",
    category: "sauces",
    name: "Sweet & chilli omáčka",
    weight: "50g",
    price: 1.5,
    desc: "Sladká chilli omáčka.",
    ingredients: ["Sweet & chilli omáčka"],
    allergens: ["12"],
    badges: ["spicy"],
  },
  {
    slug: "chipotle-dresing",
    category: "sauces",
    name: "Chipotle dresing",
    weight: "50g",
    price: 1.5,
    desc: "Pikantný chipotle dresing.",
    ingredients: ["Chipotle", "Majonéza"],
    allergens: ["3", "7", "10"],
    badges: ["spicy"],
  },
  {
    slug: "tekuty-cheddar",
    category: "sauces",
    name: "Tekutý cheddar",
    weight: "50g",
    price: 1.5,
    desc: "Roztopený tekutý cheddar.",
    ingredients: ["Cheddar"],
    allergens: ["7"],
    badges: [],
  },

  // ---------------- NÁPOJE (podľa aktuálnej ponuky) ----------------
  {
    slug: "coca-cola",
    category: "drinks",
    name: "Coca-Cola 0,33l",
    weight: "0,33l",
    price: 1.8,
    desc: "Vychladená Coca-Cola.",
    ingredients: ["Coca-Cola"],
    allergens: [],
    badges: [],
  },
  {
    slug: "kofola",
    category: "drinks",
    name: "Kofola 0,33l",
    weight: "0,33l",
    price: 1.7,
    desc: "Točená chuť v plechovke.",
    ingredients: ["Kofola"],
    allergens: [],
    badges: [],
  },
  {
    slug: "vinea",
    category: "drinks",
    name: "Vinea 0,33l",
    weight: "0,33l",
    price: 1.8,
    desc: "Sýtený hroznový nápoj.",
    ingredients: ["Vinea"],
    allergens: ["12"],
    badges: [],
  },
  {
    slug: "minmineralka",
    category: "drinks",
    name: "Minerálka 0,5l",
    weight: "0,5l",
    price: 1.5,
    desc: "Perlivá / neperlivá minerálna voda.",
    ingredients: ["Minerálna voda"],
    allergens: [],
    badges: [],
  },
];

// Expand the shared menu into per-restaurant products. priceMod lets a
// location fine-tune prices; both currently share the printed Pyro pricing.
function buildMenu(restaurantId: string, priceMod: number): Product[] {
  const counters: Partial<Record<CategoryId, number>> = {};
  return MENU.map((m) => {
    const pool = IMAGES[m.category];
    const idx = counters[m.category] ?? 0;
    counters[m.category] = idx + 1;
    return {
      id: `${restaurantId}-${m.slug}`,
      restaurantId,
      category: m.category,
      name: m.name,
      description: m.desc,
      image: pool[idx % pool.length],
      basePrice: Math.round((m.price + priceMod) * 100) / 100,
      sizes: [{ id: "std", label: m.weight, priceDelta: 0 }],
      ingredients: m.ingredients,
      allergens: m.allergens,
      badges: m.badges,
      available: true,
    };
  });
}

export const PRODUCTS: Product[] = [
  ...buildMenu("pyro", 0),
  ...buildMenu("polomarik", 0),
];

export const COUPONS: Coupon[] = [
  {
    code: "PYRO10",
    restaurantId: "pyro",
    type: "percentage",
    value: 10,
    minSubtotal: 15,
    label: "-10% na celú objednávku",
  },
  {
    code: "FREEDELIVERY",
    restaurantId: "all",
    type: "free_delivery",
    value: 0,
    minSubtotal: 20,
    label: "Doprava zdarma nad 20€",
  },
  {
    code: "HAPPY5",
    restaurantId: "all",
    type: "fixed",
    value: 5,
    minSubtotal: 25,
    label: "-5€ Happy Hour",
  },
];

// Master list of paid extras — the single source of truth for pricing. The
// server re-prices every added extra against this list, so the client can never
// influence the price. Prices follow the printed flyer (PRÍLOHY).
export const EXTRA_INGREDIENTS: { name: string; price: number }[] = [
  // 1,50 € skupina
  { name: "Cibuľa", price: 1.5 },
  { name: "Cesnak", price: 1.5 },
  { name: "Feferóny", price: 1.5 },
  { name: "Chilli omáčka", price: 1.5 },
  { name: "Vajce", price: 1.5 },
  { name: "Oregano", price: 1.5 },
  { name: "Bazalka", price: 1.5 },
  { name: "Pol / pol", price: 1.5 },
  // 2,00 € skupina
  { name: "Kukurica", price: 2.0 },
  { name: "Olivy", price: 2.0 },
  { name: "Šampiňóny", price: 2.0 },
  { name: "Artičoky", price: 2.0 },
  { name: "Kyslá kapusta", price: 2.0 },
  { name: "Paradajka", price: 2.0 },
  { name: "Jalapeño papričky", price: 2.0 },
  // 2,50 € skupina
  { name: "Šunka", price: 2.5 },
  { name: "Saláma", price: 2.5 },
  { name: "Klobása", price: 2.5 },
  { name: "Údené mäso", price: 2.5 },
  { name: "Prosciutto", price: 2.5 },
  { name: "Kuracie prsia", price: 2.5 },
  { name: "Slanina", price: 2.5 },
  { name: "Tuniak", price: 2.5 },
  { name: "Eidam", price: 2.5 },
  { name: "Niva", price: 2.5 },
  { name: "Encián", price: 2.5 },
  { name: "Mozzarella", price: 2.5 },
  { name: "Bryndza", price: 2.5 },
  { name: "Korbáčik", price: 2.5 },
  { name: "Parmezán", price: 2.5 },
  { name: "Smotana", price: 2.5 },
  { name: "Údený syr", price: 2.5 },
  { name: "Rukola", price: 2.5 },
  // langošové prílohy / omáčky
  { name: "Tatárska omáčka", price: 0.6 },
  { name: "Kečup", price: 0.6 },
  { name: "Syrový posyp", price: 0.6 },
  { name: "Cesnaková omáčka", price: 1.5 },
  { name: "Jarná cibuľka", price: 0.5 },
];

const EXTRA_PRICE = Object.fromEntries(
  EXTRA_INGREDIENTS.map((e) => [e.name, e.price])
) as Record<string, number>;

function resolveExtras(names: string[]): { name: string; price: number }[] {
  return names.map((n) => ({ name: n, price: EXTRA_PRICE[n] ?? 0 }));
}

// Pizza extras exactly as on the flyer (PRÍLOHY).
export const PIZZA_EXTRAS = resolveExtras([
  "Cibuľa", "Cesnak", "Feferóny", "Chilli omáčka", "Vajce", "Oregano",
  "Bazalka", "Pol / pol",
  "Kukurica", "Olivy", "Šampiňóny", "Artičoky", "Kyslá kapusta", "Paradajka",
  "Jalapeño papričky",
  "Šunka", "Saláma", "Klobása", "Údené mäso", "Prosciutto", "Kuracie prsia",
  "Slanina", "Tuniak", "Eidam", "Niva", "Encián", "Mozzarella", "Bryndza",
  "Korbáčik", "Parmezán", "Smotana", "Údený syr", "Rukola",
]);

// Langoš toppings — "s čím bude": sauces and cheese/topping options.
export const LANGOS_EXTRAS = resolveExtras([
  "Tatárska omáčka", "Kečup", "Syrový posyp", "Cesnaková omáčka",
  "Smotana", "Bryndza", "Slanina", "Údený syr", "Jarná cibuľka", "Šunka",
]);

// Which extras apply to a product (null = not customisable).
export function extrasForProduct(product: {
  category: string;
  name: string;
}): { name: string; price: number }[] | null {
  if (product.name.toLowerCase().includes("langoš")) return LANGOS_EXTRAS;
  if (product.category === "pizza") return PIZZA_EXTRAS;
  return null;
}

export const EXTRA_CHEESE_PRICE = 1.5;
export const STUFFED_CRUST_PRICE = 2.5;

export const REVIEWS = [
  {
    name: "Martina K.",
    rating: 5,
    text: "Najlepšia pizza v okolí! Cesto ako z pravej pece. Doručenie rýchle a horúce.",
    verified: true,
    restaurantId: "pyro",
    date: "2026-06-28",
  },
  {
    name: "Peter H.",
    rating: 5,
    text: "Objednávam pravidelne, kvalita stabilne výborná. Diablo je bomba a burgery parádne.",
    verified: true,
    restaurantId: "pyro",
    date: "2026-06-15",
  },
  {
    name: "Lucia B.",
    rating: 4,
    text: "Skvelé club sandwiche a milá obsluha. Doručenie do Stráňav za 40 minút.",
    verified: true,
    restaurantId: "polomarik",
    date: "2026-06-30",
  },
  {
    name: "Jozef M.",
    rating: 5,
    text: "Gazdovská a domáca pohoda. Odporúčam každému!",
    verified: true,
    restaurantId: "polomarik",
    date: "2026-06-20",
  },
];

export const DAY_NAMES = [
  "Pondelok",
  "Utorok",
  "Streda",
  "Štvrtok",
  "Piatok",
  "Sobota",
  "Nedeľa",
];
